before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  # - id: wireguard-for-homies
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./cmd/wireguard-for-homies/main.go
    # binary: wireguard-for-homies
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      "386": i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    # binaries:
    #   - wireguard-for-homies
    # builds:
    #   - wireguard-for-homies
    image_templates:
      - docker.io/cordalace/wireguard-for-homies:{{ .Tag }}
      - docker.io/cordalace/wireguard-for-homies:v{{ .Major }}
      - docker.io/cordalace/wireguard-for-homies:v{{ .Major }}.{{ .Minor }}
      - docker.io/cordalace/wireguard-for-homies:latest
    build_flag_templates:
      - "--pull"
      - "--label=maintainer=Azat Kurbanov <cordalace@gmail.com>"
      # label schema
      - "--label=org.label-schema.build-date={{.Date}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=org.label-schema.description=Telegram bot managed wireguard server for you and your homies"
      - "--label=org.opencontainers.image.usage=https://github.com/cordalace/wireguard-for-homies/wiki/Usage"
      - "--label=org.label-schema.url=https://github.com/cordalace/wireguard-for-homies"
      - "--label=org.label-schema.vcs-url=https://github.com/cordalace/wireguard-for-homies"
      - "--label=org.label-schema.vcs-ref={{.FullCommit}}"
      - "--label=org.label-schema.vendor=Azat Kurbanov <cordalace@gmail.com>"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.schema-version=1.0"
      # opencontainer
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.authors=Azat Kurbanov <cordalace@gmail.com>"
      - "--label=org.opencontainers.image.url=https://github.com/cordalace/wireguard-for-homies"
      - "--label=org.opencontainers.image.documentation=https://github.com/cordalace/wireguard-for-homies/wiki/Usage"
      - "--label=org.opencontainers.image.source=https://github.com/cordalace/wireguard-for-homies"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.vendor=Azat Kurbanov"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=Telegram bot managed wireguard server for you and your homies"
